-
  name: Teardown VirtualBox environment
  hosts: localhost
  tasks:
    - name: Stop DB VM
      command: VBoxManage controlvm db poweroff
      ignore_errors: yes
    - name: Stop web VM
      command: VBoxManage controlvm web poweroff
      ignore_errors: yes
    - name: Destroy web VM image
      command: VBoxManage unregistervm web --delete
      ignore_errors: yes
    - name: Destroy db VM image
      command: VBoxManage unregistervm db --delete
      ignore_errors: yes
    - name: Remove db key from ssh known hosts
      lineinfile:
        path: ~/.ssh/known_hosts
        regexp: "^{{ hostvars[\"db\"].ansible_host }}"
        state: absent
    - name: Remove web key from ssh known hosts
      lineinfile:
        path: ~/.ssh/known_hosts
        regexp: "^{{ hostvars[\"web\"].ansible_host }}"
        state: absent

